@startuml
left to right direction

[Root] --> [Users]
[Root] --> [Products]
[Root] --> [Parts]
[Root] --> [Materials]
[Root] --> [Logs]
[Root] --> [Finances]
[Root] --> [Customers]
[Root] --> [Home]
[Home] --> [HomeGreetings]
[Root] --> [Login]
[Login] --> [LoginForm]
[Parts] --> [PartsInventory]
[Parts] --> [PartsCatalog]
[Parts] --> [CreatePartModal]
[Logs] --> [Audit]
[Logs] --> [LogsList]
[Finances] --> [Summary]
[Finances] --> [Expences]
[Finances] --> [Income]
[Products] --> [ProductsInventory]
[Products] --> [ProductsCatalog]
[Customers] --> [CustomersList]
[Products] --> [CreateProductModal]
[Products] --> [ProductDetails]
[Materials] --> [MaterialsInventory]
[Materials] --> [MaterialsCatalog]
[Materials] --> [CreateMaterialsModal]
[Materials] --> [MaterialImageUploader]
[Users] --> [AddUserModal]
[Users] --> [EditUserForm]
[Users] --> [UserList]
[Users] --> [UserListActions]
@enduml
