version: '3'
services:
  server:
    depends_on:
      - db
    restart: unless-stopped
    image: docker.pkg.github.com/po-trottier/soen390-team04/epic-erp:main
    container_name: nestjs
    ports:
      - '1337:1337'
    environment:
      - PORT=1337
      - DB_URL=mongodb://db_mongo
      - DB_NAME=ERP_DB
  db:
    image: mongo:latest
    restart: unless-stopped
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    expose:
      - '27017'

volumes:
  mongodata:
