version: "3"
services:
  server:
    depends_on:
      - db
    restart: unless-stopped
    build: .
    image: nestjs:latest
    container_name: nestjs
    ports:
      - "80:1337"
    environment:
      - PORT=1337
      - DB_URL=mongodb://db_mongo
      
  db:
    image: mongo
    restart: unless-stopped
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"

volumes:
  mongodata: 