name: Digital Ocean Deployment

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: po-trottier/soen390-team04/epic-erp
        tag_with_ref: true
      
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: Copy Docker Compose Config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./docker-compose.yml"
          target: "/srv/nestjs"
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v0.1.4
        env:
          USER: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ENVS: USER,TOKEN
          SCRIPT: |
            # Navigate to the server directory
            cd /srv/nestjs
            
            # Login to the repository
            docker login docker.pkg.github.com -u $USER -p $TOKEN 
            
            # Stop running containers
            docker-compose down
            
            # Pull the new image
            docker-compose pull

            # Run a new container from a new image
            docker-compose up -d
            
            # Prune the images
            docker image prune -f
