name: Digital Ocean Deployment

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Push the Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        build_args: ENV_TOKEN=${{ secrets.ENV_PASSWORD }}
        registry: docker.pkg.github.com
        repository: po-trottier/soen390-team04/epic-erp
        cache_froms: po-trottier/soen390-team04/epic-erp:main
        tags: main

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: Unlock the ENV File
        run: npm run unlock ${{ secrets.ENV_PASSWORD }}
      - name: Copy the Docker Compose Config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          overwrite: true
          source: "./docker-compose.yml"
          target: "/srv/nestjs"
      - name: Copy the ENV File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          overwrite: true
          source: "./server/.env"
          target: "/srv/nestjs"
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v0.1.4
        env:
          USER: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ENVS: USER,TOKEN
          SCRIPT: |
            # Navigate to the server directory
            cd /srv/nestjs

            # Move the ENV file to the right directory
            mv ./server/.env .env
            rm -r ./server

            # Login to the repository
            docker login docker.pkg.github.com -u $USER -p $TOKEN

            # Stop running containers
            docker-compose down

            # Pull the new image
            docker-compose pull

            # Run a new container from a new image
            docker-compose up -d

            # Prune the images
            docker image prune -f
            docker volume prune -f
